Support file permission, creation time, last write time, ntfs attribu…
EmmaZhu/azure-storage-net pull request #1
Opened 2020-05-13 07:55 UTC by EmmaZhu

Support file permission, creation time, last write time, ntfs attributes headers in file copying

2020-05-15 06:57 UTC, jiacfan commented on Lib/ClassLibraryCommon/File/CloudFile.cs
> +            FileCopyOptions copyOptions = null,
This is unsafe, and might be hard to be perceived by user.

E.g. they used to call with StartCopy(source, null, destAccessCondition). now they can compile while destAccessCondition is assigned to sourceAccessCondition incorrectly.

Generally, adding optional parameter at end is safe. Please try to check with redmond SDK owner on this design.

2020-05-15 06:57 UTC, jiacfan commented on Lib/ClassLibraryCommon/File/CloudFile.cs
> +            FileCopyOptions copyOptions = null,
Same as above, unsafe.

2020-05-15 07:02 UTC, jiacfan commented on Lib/ClassLibraryCommon/File/CloudFile.cs
> +                if (null != copyOptions)
copy methods mentioned, if copyOptions == null, default options will be used, while here if copyOptions==null, no header will be composed, please check if this is by design.

2020-05-15 07:03 UTC, jiacfan commented on Lib/ClassLibraryCommon/File/CloudFile.cs
> +                    if (copyOptions.PreservePermissions)
Track.2 .net SDKhave this feature released, please double check behavior is same as Track.2 .net SDK.

2020-05-15 07:06 UTC, jiacfan commented on Lib/Common/Shared/Protocol/Constants.cs
> +            public const string TargetStorageVersion = "2019-07-07";
Would this affect Blob, Queue and other services? Please ensure if SDK owner are good with version bump up, and check if there could be any other changes, e.g. additional header returned for other services.

2020-05-15 07:07 UTC, jiacfan commented on Lib/Common.Split/Shared/File.Shared/FileCopyOptions.cs
> +        public FileCopyOptions()
Please check if this is align with track2 SDK.

2020-05-15 07:07 UTC, jiacfan commented on Microsoft.Azure.Storage.sln
> +		Lib\Common.Split\Shared\File.Shared\Microsoft.Azure.Storage.Common.File.projitems*{1fcc9c24-2834-4f21-a526-2f0ed09d7747}*SharedItemsImports = 5
Is this by design?

2020-05-15 07:08 UTC, jiacfan commented on Microsoft.Azure.Storage.sln
> +		{ED51F78B-EC11-4052-A9CA-5A909C8BA3B7}.Official|Any CPU.ActiveCfg = Release|Any CPU
>Release [](start = 70, length = 7)

Is this by design? Please double check if changes in this file is by design.

2020-05-15 07:08 UTC, jiacfan commented on Test/ClassLibraryCommon/File/CopyFileTest.cs
> +                    string permission = "O:S-1-5-21-2127521184-1604012920-1887927527-21560751G:S-1-5-21-2127521184-1604012920-1887927527-513D:AI(A;;FA;;;SY)(A;;FA;;;BA)(A;;0x1200a9;;;S-1-5-21-3979554
>     [](start = 16, length = 4)

nit: alignments, please check in other files

2020-05-15 07:08 UTC, jiacfan commented on Test/ClassLibraryCommon/File/CopyFileTest.cs
> +                    string permission = "O:S-1-5-21-2127521184-1604012920-1887927527-21560751G:S-1-5-21-2127521184-1604012920-1887927527-513D:AI(A;;FA;;;SY)(A;;FA;;;BA)(A;;0x1200a9;;;S-1-5-21-3979554
>     [](start = 16, length = 4)

Please ensure test coverage is equal to Track 2 on this feature.

2020-05-15 07:09 UTC, jiacfan requested changes
:clock1:

2020-05-18 03:34 UTC, JasonYang-MSFT commented on Lib/Common/Shared/Protocol/Constants.cs
> +            /// Header that specifies copy file permissions, file system attributes, creation time or last write time from the source file to the destination file.
>Header that specifies [](start = 16, length = 21)

Header value, right?

2020-05-18 03:34 UTC, JasonYang-MSFT commented on Lib/Common/Shared/Protocol/Constants.cs
> +            /// Header that specifies override file permissions on the destination file.
>Header that specifies [](start = 16, length = 21)

Header value, right?

2020-05-18 03:44 UTC, JasonYang-MSFT commented on Lib/ClassLibraryCommon/File/CloudFile.cs
> +                destAccessCondition,
>  [](start = 36, length = 1)

extra space in several lines.

2020-05-18 03:50 UTC, JasonYang-MSFT commented on Lib/Common.Split/Shared/File.Shared/FileCopyOptions.cs
> +        public bool PreserveNtfsAttributes { get; set; }
>PreserveNtfsAttributes [](start = 20, length = 22)

Preferred not use "Ntfs" to align with rest api doc: "x-ms-file-attributes "
Also, bool may not be enough for SDK. There are three state for this option: not specified, source, none.

2020-05-18 03:55 UTC, JasonYang-MSFT commented on Lib/Common.Split/Shared/File.Shared/FileCopyOptions.cs
> +        public bool PreservePermissions { get; set; }
>PreservePermissions [](start = 20, length = 19)

Same to below, there are three state of "x-ms-file-permission-copy-mode"

2020-05-18 04:25 UTC, JasonYang-MSFT commented on Lib/ClassLibraryCommon/File/CloudFile.cs
> +        /// <param name="copyOptions">An <see cref="FileCopyOptions"/> object that represents the options for the copying. If <c>null</c>, default options are applied.</param>
>default options are applied [](start = 139, length = 27)

x-ms-file-permission-copy-mode, x-ms-file-attributes, x-ms-file-creation-time , x-ms-file-last-write-time , and x-ms-file-copy-set-archive  are all optional headers, in the case of null, I think no value should be applied instead of default values.

Just like the access conditions below.

2020-05-18 04:35 UTC, JasonYang-MSFT requested changes
:clock1:

2020-05-18 07:38 UTC, EmmaZhu commented on Lib/Common.Split/Shared/File.Shared/FileCopyOptions.cs
> +        public bool PreserveNtfsAttributes { get; set; }
For file meta, if it's not null, client library will set the values in header; if it's null, client library will not set them in header, server side will copy meta data values from source.

So for the SMB properties, I think we can use the same design. If customer would want to preserve the source value ( set the preserve bool value to true), we'll set the header to source; if customer set its value (for example, creation time has a value in Properties), we'll set the value into header; If the preserve bool value is false, and no property value is set, we'll not set the header then server side will keep the origin value on destination.

2020-05-19 03:07 UTC, EmmaZhu commented on Lib/ClassLibraryCommon/File/CloudFile.cs
> +                    if (copyOptions.PreservePermissions)
We can guarantee that basic function would be the same with Track 2 SDK, but cannot guarantee interfaces. The origin interfaces between Track 1 and Track 2 are different.

2020-05-19 03:07 UTC, EmmaZhu commented on Lib/Common/Shared/Protocol/Constants.cs
> +            public const string TargetStorageVersion = "2019-07-07";
Thanks for the comments. Checked,  no more change needed.

2020-05-19 03:08 UTC, EmmaZhu commented on Lib/ClassLibraryCommon/File/CloudFile.cs
> +            FileCopyOptions copyOptions = null,
Updated.

2020-05-19 03:08 UTC, EmmaZhu commented on Lib/ClassLibraryCommon/File/CloudFile.cs
> +            FileCopyOptions copyOptions = null,
Updated.

2020-05-19 03:08 UTC, EmmaZhu commented on Lib/ClassLibraryCommon/File/CloudFile.cs
> +                if (null != copyOptions)
Updated. Thanks for the comments.

2020-05-19 03:09 UTC, EmmaZhu commented on Microsoft.Azure.Storage.sln
> +		Lib\Common.Split\Shared\File.Shared\Microsoft.Azure.Storage.Common.File.projitems*{1fcc9c24-2834-4f21-a526-2f0ed09d7747}*SharedItemsImports = 5
Updated.

2020-05-19 03:11 UTC, EmmaZhu commented on Lib/Common.Split/Shared/File.Shared/FileCopyOptions.cs
> +        public bool PreservePermissions { get; set; }
Updated

2020-05-19 13:37 UTC, JasonYang-MSFT approved these changes

2020-05-21 05:26 UTC, EmmaZhu commented on Lib/Common.Split/Shared/File.Shared/FileCopyOptions.cs
> +        public FileCopyOptions()
The whole function is the same with Track 2 SDK, the interface cannot be totally the same. Here the change will follow old Track 1 SDK's interface.

2020-05-21 05:39 UTC, jiacfan approved these changes
:shipit:

2020-05-28 01:50 UTC, closed without merging